import type { RepoReview } from './types'
import type { HealthResult } from './health'
import { formatCompactNumber } from './format'

export function buildMarkdownReport(review: RepoReview, health: HealthResult): string {
  const { info, contributors, languages } = review
  const langList = Object.keys(languages).slice(0, 6).join(', ') || 'n/a'
  const topContributors = contributors
    .slice(0, 5)
    .map((c) => `- [${c.login}](${c.html_url}) — ${c.contributions} commits`)
    .join('\n')

  return `# ${info.full_name} — Repo Review

${info.description ?? ''}

**Health score:** ${health.overall}/100

| Metric | Value |
| --- | --- |
| Stars | ${formatCompactNumber(info.stargazers_count)} |
| Forks | ${formatCompactNumber(info.forks_count)} |
| Open issues | ${review.openIssuesOnly} |
| Open PRs | ${review.openPRs} |
| Contributors (top 10) | ${contributors.length} |
| Languages | ${langList} |
| License | ${info.license?.name ?? 'None'} |

## Health factors

${health.factors.map((f) => `- **${f.label}** (${f.score}/100): ${f.detail}`).join('\n')}

## Top contributors

${topContributors || 'n/a'}

---
Generated by Repo Reviewer · ${info.html_url}
`
}

export function downloadMarkdown(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
